//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal class Binary : IExpression {
        
        public IExpression left;
        
        public Token op;
        
        public IExpression right;
        
        public Binary(IExpression left, Token op, IExpression right) {
            this.left = left;
            this.op = op;
            this.right = right;
        }
        
        public object Accept(IVisitor visitor) {
            return visitor.VisitBinary(this);
        }
    }
}
