//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class CallExpression : IExpression {
        
        public IExpression callee;
        
        public Token parenthesis;
        
        public List<IExpression> arguments;
        
        public CallExpression(IExpression callee, Token parenthesis, List<IExpression> arguments) {
            this.callee = callee;
            this.parenthesis = parenthesis;
            this.arguments = arguments;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitCallExpression(this);
        }
    }
}
