//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class ClassStatement : IStatement {
        
        public Token name;
        
        public VariableExpression superclass;
        
        public List<FunctionStatement> methods;
        
        public List<VariableStatement> properties;
        
        public List<LetStatement> readOnlyProperties;
        
        public ClassStatement(Token name, VariableExpression superclass, List<FunctionStatement> methods, List<VariableStatement> properties, List<LetStatement> readOnlyProperties) {
            this.name = name;
            this.superclass = superclass;
            this.methods = methods;
            this.properties = properties;
            this.readOnlyProperties = readOnlyProperties;
        }
        
        public object Accept(IStatementVisitor visitor) {
            return visitor.VisitClassStatement(this);
        }
    }
}
