//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class FunctionStatement : IStatement {
        
        public Token name;
        
        public List<(Token, Token)> parameters;
        
        public Token returnType;
        
        public List<IStatement> body;
        
        public FunctionStatement(Token name, List<(Token, Token)> parameters, Token returnType, List<IStatement> body) {
            this.name = name;
            this.parameters = parameters;
            this.returnType = returnType;
            this.body = body;
        }
        
        public object Accept(IStatementVisitor visitor) {
            return visitor.VisitFunctionStatement(this);
        }
    }
}
