//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class GetExpression : IExpression {
        
        public IExpression source;
        
        public Token name;
        
        public GetExpression(IExpression source, Token name) {
            this.source = source;
            this.name = name;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitGetExpression(this);
        }
    }
}
