//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal class Grouping : IExpression {
        
        public IExpression expression;
        
        public Grouping(IExpression expression) {
            this.expression = expression;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitGrouping(this);
        }
    }
}
