//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal interface IExpressionVisitor {
        
        object VisitAssignmentExpression(AssignmentExpression assignmentexpression);
        
        object VisitBinaryExpression(BinaryExpression binaryexpression);
        
        object VisitGroupingExpression(GroupingExpression groupingexpression);
        
        object VisitLiteralExpression(LiteralExpression literalexpression);
        
        object VisitUnaryExpression(UnaryExpression unaryexpression);
        
        object VisitVariableExpression(VariableExpression variableexpression);
        
        object VisitLogicalExpression(LogicalExpression logicalexpression);
        
        object VisitCallExpression(CallExpression callexpression);
        
        object VisitGetExpression(GetExpression getexpression);
        
        object VisitSetExpression(SetExpression setexpression);
        
        object VisitThisExpression(ThisExpression thisexpression);
        
        object VisitSuperExpression(SuperExpression superexpression);
    }
}
