//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal interface IExpressionVisitor {
        
        object VisitBinary(Binary binary);
        
        object VisitGrouping(Grouping grouping);
        
        object VisitLiteral(Literal literal);
        
        object VisitUnary(Unary unary);
    }
}
