//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class IfStatement : IStatement {
        
        public IExpression condition;
        
        public IStatement thenBranch;
        
        public IStatement elseBranch;
        
        public IfStatement(IExpression condition, IStatement thenBranch, IStatement elseBranch) {
            this.condition = condition;
            this.thenBranch = thenBranch;
            this.elseBranch = elseBranch;
        }
        
        public object Accept(IStatementVisitor visitor) {
            return visitor.VisitIfStatement(this);
        }
    }
}
