//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal interface IStatementVisitor {
        
        object VisitBlockStatement(BlockStatement blockstatement);
        
        object VisitPrintStatement(PrintStatement printstatement);
        
        object VisitExpressionStatement(ExpressionStatement expressionstatement);
        
        object VisitVariableStatement(VariableStatement variablestatement);
        
        object VisitIfStatement(IfStatement ifstatement);
        
        object VisitWhileStatement(WhileStatement whilestatement);
        
        object VisitForStatement(ForStatement forstatement);
        
        object VisitFunctionStatement(FunctionStatement functionstatement);
        
        object VisitReturnStatement(ReturnStatement returnstatement);
    }
}
