//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal class Literal : IExpression {
        
        public object value;
        
        public Literal(object value) {
            this.value = value;
        }
        
        public object Accept(IVisitor visitor) {
            return visitor.VisitLiteral(this);
        }
    }
}
