//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class ReturnStatement : IStatement {
        
        public Token keyword;
        
        public IExpression value;
        
        public ReturnStatement(Token keyword, IExpression value) {
            this.keyword = keyword;
            this.value = value;
        }
        
        public object Accept(IStatementVisitor visitor) {
            return visitor.VisitReturnStatement(this);
        }
    }
}
