//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class SetExpression : IExpression {
        
        public IExpression source;
        
        public Token name;
        
        public IExpression value;
        
        public SetExpression(IExpression source, Token name, IExpression value) {
            this.source = source;
            this.name = name;
            this.value = value;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitSetExpression(this);
        }
    }
}
