//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class SuperExpression : IExpression {
        
        public Token keyword;
        
        public Token method;
        
        public SuperExpression(Token keyword, Token method) {
            this.keyword = keyword;
            this.method = method;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitSuperExpression(this);
        }
    }
}
