//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class ThisExpression : IExpression {
        
        public Token keyword;
        
        public ThisExpression(Token keyword) {
            this.keyword = keyword;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitThisExpression(this);
        }
    }
}
