//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal class UnaryExpression : IExpression {
        
        public Token op;
        
        public IExpression right;
        
        public UnaryExpression(Token op, IExpression right) {
            this.op = op;
            this.right = right;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitUnaryExpression(this);
        }
    }
}
