//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class VariableStatement : IStatement {
        
        public Token name;
        
        public IExpression initializer;
        
        public VariableStatement(Token name, IExpression initializer) {
            this.name = name;
            this.initializer = initializer;
        }
        
        public object Accept(IStatementVisitor visitor) {
            return visitor.VisitVariableStatement(this);
        }
    }
}
