//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    
    
    internal class VariableExpression : IExpression {
        
        public Token name;
        
        public VariableExpression(Token name) {
            this.name = name;
        }
        
        public object Accept(IExpressionVisitor visitor) {
            return visitor.VisitVariableExpression(this);
        }
    }
}
