//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace CodingFoxLang.Compiler {
    using CodingFoxLang.Compiler.Scanner;
    using System.Collections.Generic;
    
    
    internal class WhileStatement : IStatement {
        
        public IExpression condition;
        
        public IStatement body;
        
        public WhileStatement(IExpression condition, IStatement body) {
            this.condition = condition;
            this.body = body;
        }
        
        public object Accept(IStatementVisitor visitor) {
            return visitor.VisitWhileStatement(this);
        }
    }
}
